#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pyreadline
Version  : 2.1
Release  : 1
URL      : https://files.pythonhosted.org/packages/bc/7c/d724ef1ec3ab2125f38a1d53285745445ec4a8f19b9bb0761b4064316679/pyreadline-2.1.zip
Source0  : https://files.pythonhosted.org/packages/bc/7c/d724ef1ec3ab2125f38a1d53285745445ec4a8f19b9bb0761b4064316679/pyreadline-2.1.zip
Summary  : A python implmementation of GNU readline.
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pyreadline-python3
Requires: pyreadline-license
Requires: pyreadline-python
BuildRequires : buildreq-distutils3

%description
The pyreadline package is a python implementation of GNU readline functionality
        it is based on the ctypes based UNC readline package by Gary Bishop.
        It is not complete. It has been tested for use with windows 2000 and windows xp.
        
        * pyreadline 2.1 <2015-09-16>
        
          This is a bugfix release to make pyreadline work with python 3.5.

%package license
Summary: license components for the pyreadline package.
Group: Default

%description license
license components for the pyreadline package.


%package python
Summary: python components for the pyreadline package.
Group: Default
Requires: pyreadline-python3

%description python
python components for the pyreadline package.


%package python3
Summary: python3 components for the pyreadline package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pyreadline package.


%prep
%setup -q -n pyreadline-2.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1534861223
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/pyreadline
cp doc/COPYING %{buildroot}/usr/share/doc/pyreadline/doc_COPYING
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/pyreadline/doc_COPYING

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
